version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: trading-platform-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: trading-platform-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trading_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET:-YourSecretKeyHere}
      ELASTIC_EMAIL_APIKEY: ${ELASTIC_EMAIL_APIKEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    restart: always

  frontend:
    image: node:16-alpine
    container_name: trading-platform-frontend
    working_dir: /app
    volumes:
      - ../trading-platform-frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  mysql-data: 